### ISSUE TITLE
JSON sample for calling a custom action

### ISSUE THREAD

**Issue by PavelBGetp** [ZupIT/beagle-docs#804]
Hi, 
I'm trying to build an Android POC with beagle, just to check if we can use it in our product. I've created a simple action, but could not add it to a button. Can You please provide a sample json for a button that executes a custom action from this page: https://docs.usebeagle.io/v1.10/android/customization/action/simple-action/

**Comment by carlossteinzup** [comment]
**Hello @PavelBGetp**. Thank you for your contact. I will be following up on this issue with you.

In order to add an action to a button, it is necessary to declare it as the button `onPress` action. 
Here, in this **example**, you can see how we add an `Alert Action` to a button

```
{
  "_beagleComponent_": "beagle:button",
  "text": "Beagle Button",
  "onPress": [
    {
      "_beagleAction_": "beagle:alert",
      "message": "Example button."
    }
  ]
}
```

But, If you wish to add a **custom action** called `myCustomAction` for this button, you must do the same as above, but add the **`custom action name`** instead, as in the example below:

```
{
  "_beagleComponent_": "beagle:button",
  "text": "Beagle Button",
  "onPress": [
    {
      "_beagleAction_": "custom:myCustomAction",
      "message": "Example Custom Action."
    }
  ]
}
```

**Important notice**: Please keep in mind that generally these JSONs are created through a backend application with Beagle. It is important to proceed like this since Beagle will build this JSON schema according to its components contract. 

It is also important to notice that you must create this action on the backend as well, and use the same class name as in the front-end, for example, the same custom action code for the backed would be:
```
@RegisterAction
class myCustomAction:Action
```

I hope this information had helped you understand what should be done!
Please feel free to contact us again here or via our [forum](https://forum.zup.com.br/c/en/beagle/12)
